/**
 * Landing-page copy, EN + ES. Structure of the two languages must stay
 * identical (DESIGN.md invariant) — enforced by src/app/lp-guards.test.ts,
 * which also pins the pricing facts to PLAN_LIMITS (Free 3/mo no card,
 * Pro 100/mo, "Unlimited" on Team only) and the HUMANIZE banned-word list.
 * Icons are language-independent and live in HomePageClient.tsx.
 */
export const T = {
  en: {
    nav: { how: "How it works", pricing: "Pricing", reviews: "Examples", blog: "Blog", dashboard: "Dashboard", signin: "Sign in", cta: "Start free" },
    hero: {
      headline1: "Turn one live lot into",
      headline2: "something your buyer can react to.",
      sub: "Enter a lot and the buyer's requirements. SplanAI drafts three concept directions with neighborhood data and payment assumptions, ready to review in about 30 seconds.",
      ctaPrimary: "Try it on a sample lot",
      ctaSecondary: "Start free — 3 proposals a month",
      stat1: { value: "3 directions", label: "per lot" },
      stat2: { value: "~30 sec", label: "first draft" },
      stat3: { value: "No card", label: "to start" },
    },
    trust: { label: "Powered by" },
    pain: {
      heading: "Sound familiar?",
      sub: "The three biggest deal-killers for home builders today.",
      items: [
        {
          headline: "Clients ask for a proposal. You spend 3 days on it.",
          body: "By then, they've moved on. Slow proposals don't just lose time — they lose deals.",
          solution: "SplanAI generates 3 plans in 30 seconds.",
        },
        {
          headline: "You show a floor plan. They can't visualize it.",
          body: "A static sketch doesn't sell. Clients need to see their future home — with real neighborhood data and financing numbers.",
          solution: "Share a live portal. Clients explore on their own.",
        },
        {
          headline: "You send a PDF. It sits in their inbox.",
          body: "You have no idea if they even opened it. While you wait, a competitor is already following up.",
          solution: "Know exactly when they open it, and which plan they love.",
        },
      ],
    },
    how: {
      heading: "From lot to client presentation in 30 seconds.",
      steps: [
        { step: "01", title: "Enter lot details", desc: "Lot size, budget, family size. Optional: city & state for neighborhood data." },
        { step: "02", title: "AI generates 3 plans", desc: "Get three distinct home concepts with neighborhood data, avg rent, and mortgage estimates built in." },
        { step: "03", title: "Share with your client", desc: "Download a branded PDF or send a unique link. Get notified when they view it." },
      ],
    },
    diff: {
      heading: "The sales layer between your lot and the signed contract.",
      sub: "SplanAI is a sales tool — not a design tool.",
      items: [
        { title: "Neighborhood Intelligence", desc: "Auto-fetch nearby schools, police/fire stations, and market rents via Google Maps and RentCast." },
        { title: "Branded PDF in One Click", desc: "Professional proposals with your logo, room breakdown, and cost estimate. Print-ready." },
        { title: "Real-Time Client Tracking", desc: "Know the moment a client opens the link, see which concept they engaged, and send a ready-made follow-up." },
        { title: "Price & Payment, Confirmed With You", desc: "I'll confirm the build-price and payment assumptions with you, so the numbers your buyer sees are ones you can stand behind." },
        { title: "Layout at a Glance", desc: "A clean visual of each concept's room layout — easy to read, no blueprint required." },
        { title: "A Portal That Stays Alive", desc: "Favorites, saved settings, and a 'new since your last visit' nudge bring buyers back." },
      ],
    },
    mission: {
      heading: "Built for builders who sell homes, not draw blueprints.",
      body: "SplanAI isn't a design tool. It's the sales layer between your lot and your client's signature — home concept proposals, market data, financing, and client intelligence, all in one place.",
    },
    pricing: {
      heading: "Simple, transparent pricing",
      sub: "Start free. Upgrade when you're ready.",
      free: { label: "Free", price: "$0", note: "No credit card required", features: ["3 proposal generations / month", "SplanAI branded PDF export", "Neighborhood & market data", "Client sharing portal + view tracking", "All room types", "Email support"], cta: "Get started free" },
      pro: { label: "Pro", price: "$49", period: "/mo", note: "14-day free trial, then $49/mo. Cancel anytime before it ends.", badge: "MOST POPULAR", features: ["Everything in Free, plus:", "100 proposals/mo · 1 seat", "Branded PDF with your logo (Powered by SplanAI footer included)", "MLS listing data — real lot size & zoning in every plan (requires your MLS license)", "Priority support"], cta: "Start 14-day free trial" },
      team: { label: "Team", price: "$149", period: "/mo", note: "14-day free trial, then $149/mo. Cancel anytime before it ends.", features: ["Everything in Pro, plus:", "Unlimited proposals/mo (fair use*) · up to 15 seats", "Team dashboard & member KPIs", "White-label PDF — your logo only, zero SplanAI branding", "Dedicated support"], cta: "Start 14-day free trial", redirecting: "Redirecting…" },
      custom: { label: "Custom", features: ["Everything in Team, plus:", "Higher generation volume", "Priority onboarding", "Multiple MLS connections", "Pricing sized to your sales team"], cta: "Talk to us" },
      footer: "All plans include PDF export · No hidden fees · Cancel anytime",
    },
    faq: [
      { q: "How does MLS data work?", a: "You connect your own MLS license via Trestle. Listing data is displayed in real time — never stored or redistributed. You use MLS data under your own license and remain responsible for your MLS board's rules and any applicable IDX requirements." },
      { q: "What data sources do you use?", a: "SplanAI uses Google Maps (neighborhood places & geocoding), RentCast (market rent and sale price data), the St. Louis Fed (FRED) for current mortgage rates, Anthropic Claude AI (proposal generation), and optionally your MLS license for listing data. All sources are listed on your dashboard." },
      { q: "Is my client data secure?", a: "Yes. All data is stored in a Supabase database with row-level security — only you can access your plans and client links. Shared links expire and can be deactivated anytime. We never sell your data." },
      { q: "Does it work in my area?", a: "AI plan generation works with the lot details you enter. Neighborhood and market data depend on our data providers' coverage, and MLS connectivity depends on your local MLS board." },
      { q: "Can I cancel anytime?", a: "Absolutely. Cancel from your dashboard in one click — no phone calls, no forms. Your Pro access continues until the end of your billing period." },
    ],
    security: {
      heading: "Your data stays yours.",
      sub: "Built with privacy and compliance in mind.",
      items: [
        { text: "Client data is never used to train AI models" },
        { text: "All plans and portal activity are encrypted" },
        { text: "Audit logs on every data call" },
      ],
    },
    ctaBanner: { heading: "Ready when you have a lot in hand.", sub: "Three concepts, neighborhood data, and payment assumptions — free to try, no card.", cta: "Start free" },
    footer: "© 2026 SplanAI. Built for home builders.",
    faqHeading: "Frequently Asked Questions",
    reassure: ["No credit card to start free", "14-day trial on Pro & Team", "Cancel anytime, no questions"],
    customPrice: "For 50+ employees",
    customPriceSub: "Volume pricing · Talk to us",
    wyg: {
      eyebrow: "What you get",
      heading: "A real sample concept, built for your lot.",
      sub: "A real sample concept from a live SplanAI session — generated with real AI and real market data.",
      note: "Personally built by the founder. No design agency. No fluff.",
      sec: "~30 sec",
      s1Title: "AI generates 3 distinct home concept proposals",
      estRange: "Est. range — finishes-dependent.",
      sqft: "sq ft",
      s1Foot: "A real sample concept — matches the live portal at /s/nfhkewvz",
      s2Title: "Share a live client portal — one click",
      s2Body: "Your client gets a personal portal with all 3 plans — floor-plan diagrams, cost ranges, and a mortgage calculator they can adjust. If they request pre-qualification, book a meeting, or tap \"I'm interested,\" you get an email right away. You also see the moment they open it.",
      s2Cta: "See a live portal example →",
      s3aTitle: "Download branded PDF",
      s3aBody: "Professional PDF with your logo, full room breakdown, cost range and mortgage estimate, and neighborhood data. Print-ready for client meetings.",
      s3bTitle: "MLS-enriched plans",
      s3bBody: "Connect your own MLS license via Trestle to auto-fill real lot size & zoning into every concept plan. Every data call is audit-logged. Requires your own MLS license.",
    },
  },
  es: {
    nav: { how: "Cómo funciona", pricing: "Precios", reviews: "Ejemplos", blog: "Blog", dashboard: "Panel", signin: "Iniciar sesión", cta: "Empieza gratis" },
    hero: {
      headline1: "Convierte un lote real en algo",
      headline2: "a lo que tu comprador pueda reaccionar.",
      sub: "Ingresa un lote y los requisitos del comprador. SplanAI prepara tres direcciones de concepto con datos del vecindario y supuestos de pago, listas para revisar en unos 30 segundos.",
      ctaPrimary: "Pruébalo con un lote de muestra",
      ctaSecondary: "Empieza gratis — 3 propuestas al mes",
      stat1: { value: "3 direcciones", label: "por lote" },
      stat2: { value: "~30 seg", label: "primer borrador" },
      stat3: { value: "Sin tarjeta", label: "para empezar" },
    },
    trust: { label: "Con tecnología de" },
    pain: {
      heading: "¿Te suena familiar?",
      sub: "Los tres mayores obstáculos para los constructores hoy.",
      items: [
        {
          headline: "El cliente pide una propuesta. Pasas 3 días haciéndola.",
          body: "Para entonces, ya se fue. Las propuestas lentas no solo pierden tiempo — pierden contratos.",
          solution: "SplanAI genera 3 propuestas en 30 segundos.",
        },
        {
          headline: "Muestras un plano. No lo visualizan.",
          body: "Un boceto estático no vende. Los clientes necesitan ver su futuro hogar — con datos del vecindario y números de financiamiento reales.",
          solution: "Comparte un portal en vivo. Los clientes exploran solos.",
        },
        {
          headline: "Envías un PDF. Se queda en su bandeja.",
          body: "No sabes si lo abrieron. Mientras esperas, un competidor ya está haciendo seguimiento.",
          solution: "Sabe exactamente cuándo lo abren y qué propuesta les gusta.",
        },
      ],
    },
    how: {
      heading: "Del lote a la presentación al cliente en 30 segundos.",
      steps: [
        { step: "01", title: "Ingresa los datos del lote", desc: "Tamaño, presupuesto, familia. Opcional: ciudad y estado para datos del vecindario." },
        { step: "02", title: "La IA genera 3 propuestas", desc: "Obtén tres conceptos distintos con datos del vecindario, renta promedio y estimados de hipoteca incluidos." },
        { step: "03", title: "Comparte con tu cliente", desc: "Descarga el PDF o envía un enlace único. Recibe una notificación cuando lo vean." },
      ],
    },
    diff: {
      heading: "La capa de ventas entre tu lote y el contrato firmado.",
      sub: "SplanAI es una herramienta de ventas — no de diseño.",
      items: [
        { title: "Inteligencia de Vecindario", desc: "Escuelas, estaciones de policía/bomberos y renta del mercado vía Google Maps y RentCast." },
        { title: "PDF con Tu Marca en Un Clic", desc: "Propuestas profesionales con tu logo, distribución de habitaciones y estimado de costo." },
        { title: "Seguimiento en Tiempo Real", desc: "Sabe al instante cuando tu cliente abre el enlace, qué concepto le interesa, y envía un seguimiento listo para usar." },
        { title: "Precio y Pago, Confirmados Contigo", desc: "Confirmaré contigo el precio de construcción y los supuestos de pago, para que los números que ve tu comprador sean unos que puedas respaldar." },
        { title: "Distribución de un Vistazo", desc: "Una vista clara de la distribución de cada concepto, fácil de entender." },
        { title: "Un Portal que Sigue Vivo", desc: "Favoritos, ajustes guardados y un aviso de 'novedades desde tu última visita' hacen volver al cliente." },
      ],
    },
    mission: {
      heading: "Construido para constructores que venden casas, no que dibujan planos.",
      body: "SplanAI no es una herramienta de diseño. Es la capa de ventas entre tu lote y la firma de tu cliente — propuestas, datos de mercado, financiamiento e inteligencia del cliente, todo en un solo lugar.",
    },
    pricing: {
      heading: "Precios simples y transparentes",
      sub: "Empieza gratis. Actualiza cuando estés listo.",
      free: { label: "Gratis", price: "$0", note: "Sin tarjeta de crédito", features: ["3 generaciones / mes", "PDF con marca SplanAI", "Datos de vecindario y mercado", "Portal para clientes + seguimiento de vistas", "Todos los tipos de habitación", "Soporte por email"], cta: "Empezar gratis" },
      pro: { label: "Pro", price: "$49", period: "/mes", note: "14 días de prueba gratis, luego $49/mes. Cancela antes que termine.", badge: "MÁS POPULAR", features: ["Todo lo de Gratis, más:", "100 propuestas/mes · 1 usuario", "PDF con tu logo (pie Powered by SplanAI incluido)", "Datos MLS — tamaño del lote y zonificación reales en cada propuesta (requiere tu licencia MLS)", "Soporte prioritario"], cta: "Iniciar prueba gratis" },
      team: { label: "Equipo", price: "$149", period: "/mes", note: "14 días de prueba gratis, luego $149/mes. Cancela antes que termine.", features: ["Todo lo de Pro, más:", "Propuestas ilimitadas/mes (uso justo*) · hasta 15 usuarios", "Panel de equipo y KPIs por miembro", "PDF sin marca — solo tu logo, sin branding de SplanAI", "Soporte dedicado"], cta: "Iniciar prueba gratis", redirecting: "Redirigiendo…" },
      custom: { label: "Custom", features: ["Todo lo de Equipo, más:", "Mayor volumen de generaciones", "Incorporación prioritaria", "Múltiples conexiones MLS", "Precio según tu equipo de ventas"], cta: "Contáctanos" },
      footer: "Todos los planes incluyen PDF · Sin costos ocultos · Cancela cuando quieras",
    },
    faq: [
      { q: "¿Cómo funcionan los datos MLS?", a: "Conectas tu propia licencia MLS vía Trestle. Los datos de listados se muestran en tiempo real — nunca se almacenan ni se redistribuyen. Los usas bajo tu propia licencia MLS y eres responsable de las reglas de tu junta MLS y de los requisitos IDX aplicables." },
      { q: "¿Qué fuentes de datos usa?", a: "Google Maps (vecindario y geocodificación), RentCast (datos de renta y precios de venta del mercado), la Reserva Federal de St. Louis (FRED) para tasas hipotecarias, Anthropic Claude AI (generación de propuestas) y opcionalmente tu licencia MLS para datos de listados." },
      { q: "¿Mis datos de clientes son seguros?", a: "Sí. Todos los datos se almacenan con seguridad de nivel de fila en Supabase — solo tú accedes a tus propuestas y enlaces. Los enlaces compartidos se pueden desactivar en cualquier momento." },
      { q: "¿Funciona en mi zona?", a: "La generación de propuestas funciona con los datos del lote que ingresas. Los datos de vecindario y mercado dependen de la cobertura de nuestros proveedores, y la conectividad MLS depende de tu junta MLS local." },
      { q: "¿Puedo cancelar en cualquier momento?", a: "Por supuesto. Cancela desde tu panel con un solo clic — sin llamadas telefónicas ni formularios. Tu acceso Pro continúa hasta el final del período de facturación." },
    ],
    security: {
      heading: "Tus datos son tuyos.",
      sub: "Construido con privacidad y cumplimiento en mente.",
      items: [
        { text: "Los datos de clientes nunca se usan para entrenar modelos de IA" },
        { text: "Todas las propuestas y actividad del portal están encriptadas" },
        { text: "Registros de auditoría en cada consulta de datos" },
      ],
    },
    ctaBanner: { heading: "Listo cuando tengas un lote en mano.", sub: "Tres conceptos, datos del vecindario y supuestos de pago — pruébalo gratis, sin tarjeta.", cta: "Empieza gratis" },
    footer: "© 2026 SplanAI. Construido para constructores.",
    faqHeading: "Preguntas frecuentes",
    reassure: ["Sin tarjeta para empezar gratis", "Prueba de 14 días en Pro y Equipo", "Cancela cuando quieras, sin preguntas"],
    customPrice: "Para equipos de 50+ empleados",
    customPriceSub: "Precio por volumen · Hablemos",
    wyg: {
      eyebrow: "Lo que obtienes",
      heading: "Un concepto de muestra real, hecho para tu lote.",
      sub: "Un concepto de muestra real de una sesión en vivo de SplanAI — generado con IA real y datos de mercado reales.",
      note: "Creado personalmente por el fundador. Sin agencia de diseño. Sin rodeos.",
      sec: "~30 seg",
      s1Title: "La IA genera 3 propuestas de concepto distintas",
      estRange: "Rango est. — depende de los acabados.",
      sqft: "pies²",
      s1Foot: "Un concepto de muestra real — coincide con el portal en vivo en /s/nfhkewvz",
      s2Title: "Comparte un portal de cliente en vivo — un clic",
      s2Body: "Tu cliente recibe un portal personal con las 3 propuestas — diagramas del plano, rangos de costo y una calculadora hipotecaria que puede ajustar. Si solicita precalificación, agenda una reunión o toca \"Me interesa\", recibes un email al instante. También ves el momento en que lo abre.",
      s2Cta: "Ver un portal en vivo de ejemplo →",
      s3aTitle: "Descarga un PDF con tu marca",
      s3aBody: "PDF profesional con tu logo, desglose completo de habitaciones, rango de costo y estimado de hipoteca, y datos del vecindario. Listo para imprimir para reuniones con clientes.",
      s3bTitle: "Planes enriquecidos con MLS",
      s3bBody: "Conecta tu propia licencia MLS vía Trestle para autocompletar el tamaño real del lote y la zonificación en cada concepto. Cada consulta queda registrada en auditoría. Requiere tu propia licencia MLS.",
    },
  },
} as const;

export type Lang = keyof typeof T;
